regression_metric:
  class_path: comet.models.RegressionMetric
  init_args:
    nr_frozen_epochs: 0.4
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-05
    learning_rate: 3.0e-05
    layerwise_decay: 0.95
    encoder_model: XLM-RoBERTa
    pretrained_model: xlm-roberta-large
    pool: avg
    layer: mix
    dropout: 0.1
    batch_size: 2
    train_data: data/2017-da_toy.csv
    validation_data: data/2017-da_toy.csv
    load_weights_from_checkpoint: /opt/tiger/fake_arnold/fairseq_mrt/COMET_mello/checkpoints/wmt20-comet-da.ckpt
    hidden_sizes:
      - 3072
      - 1536

trainer: trainer.yaml
early_stopping: early_stopping.yaml
model_checkpoint: model_checkpoint.yaml